import { IconDefinition } from '@ant-design/icons-angular';
import {
  HomeOutline,
  SolutionOutline,
  BarChartOutline,
  FileDoneOutline,
  ProfileOutline,
  SearchOutline,
  ContainerOutline,
  CalendarOutline,
  BookOutline,
  PlusOutline,
  UnorderedListOutline,
  PieChartOutline,
  TeamOutline,
  UserOutline,
  CreditCardOutline,
  FontSizeOutline,
  EnvironmentOutline,
  FileOutline,
  ContactsOutline,
  TagsOutline,
  FileTextOutline,
  CheckCircleOutline,
  QuestionCircleOutline,
  SettingOutline,
  ApiOutline,
  MenuOutline
} from '@ant-design/icons-angular/icons';

export const NZ_ICONS: IconDefinition[] = [
  HomeOutline,
  SolutionOutline,
  BarChartOutline,
  FileDoneOutline,
  ProfileOutline,
  SearchOutline,
  ContainerOutline,
  CalendarOutline,
  BookOutline,
  PlusOutline,
  UnorderedListOutline,
  PieChartOutline,
  TeamOutline,
  UserOutline,
  CreditCardOutline,
  FontSizeOutline,
  EnvironmentOutline,
  FileOutline,
  ContactsOutline,
  TagsOutline,
  FileTextOutline,
  CheckCircleOutline,
  QuestionCircleOutline,
  SettingOutline,
  ApiOutline,
  MenuOutline
  // Thêm các icon khác nếu cần
];
