package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ThongTinCapNhatTaiSanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThongTinCapNhatTaiSanAllPropertiesEquals(ThongTinCapNhatTaiSan expected, ThongTinCapNhatTaiSan actual) {
        assertThongTinCapNhatTaiSanAutoGeneratedPropertiesEquals(expected, actual);
        assertThongTinCapNhatTaiSanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThongTinCapNhatTaiSanAllUpdatablePropertiesEquals(
        ThongTinCapNhatTaiSan expected,
        ThongTinCapNhatTaiSan actual
    ) {
        assertThongTinCapNhatTaiSanUpdatableFieldsEquals(expected, actual);
        assertThongTinCapNhatTaiSanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThongTinCapNhatTaiSanAutoGeneratedPropertiesEquals(
        ThongTinCapNhatTaiSan expected,
        ThongTinCapNhatTaiSan actual
    ) {
        assertThat(expected)
            .as("Verify ThongTinCapNhatTaiSan auto generated properties")
            .satisfies(e -> assertThat(e.getIdCapNhat()).as("check idCapNhat").isEqualTo(actual.getIdCapNhat()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThongTinCapNhatTaiSanUpdatableFieldsEquals(ThongTinCapNhatTaiSan expected, ThongTinCapNhatTaiSan actual) {
        assertThat(expected)
            .as("Verify ThongTinCapNhatTaiSan relevant properties")
            .satisfies(e -> assertThat(e.getTenTaiSan()).as("check tenTaiSan").isEqualTo(actual.getTenTaiSan()))
            .satisfies(e -> assertThat(e.getThongTinTaiSan()).as("check thongTinTaiSan").isEqualTo(actual.getThongTinTaiSan()))
            .satisfies(e -> assertThat(e.getNgayCapNhat()).as("check ngayCapNhat").isEqualTo(actual.getNgayCapNhat()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThongTinCapNhatTaiSanUpdatableRelationshipsEquals(
        ThongTinCapNhatTaiSan expected,
        ThongTinCapNhatTaiSan actual
    ) {
        assertThat(expected)
            .as("Verify ThongTinCapNhatTaiSan relationships")
            .satisfies(e -> assertThat(e.getTaiSan()).as("check taiSan").isEqualTo(actual.getTaiSan()))
            .satisfies(e -> assertThat(e.getDanhMucLoaiTaiSan()).as("check danhMucLoaiTaiSan").isEqualTo(actual.getDanhMucLoaiTaiSan()));
    }
}
